### ISSUE TITLE
choco: Add a checksum

### ISSUE THREAD

**Issue by naveen521kk** [rstudio/tinytex-releases#30]
Currently https://github.com/rstudio/tinytex-releases/blob/a3374122731e2013319c2ff66f2559b1225a6afb/choco/tools/chocolateyinstall.ps1#L8 has a empty checksum, and that shouldn't be the case. I think some automatic updator has gone wrong.

**Comment by yihui** [comment]
Yes, the Github action definitely has gone wrong some time ago (maybe in May), but I don't know how. I just pushed a possible fix and will trigger a new release soon. Let's see if it's really fixed in a few minutes after Github action is done.

**Comment by yihui** [comment]
Should be fixed now (8841f4435ea4ea8104450c74abc942c702600bbc has got the checksum).

**Comment by naveen521kk** [comment]
Thanks!
