### ISSUE TITLE
Installation is still painful

### ISSUE THREAD

**Issue by aokman** [rstudio/tinytex-releases#38]
I came here from Tex Live, the installation of Tex Live is fairly smooth, you just download a installer, press a button it will all the work for you. But Tex Live is too larg, and it takes too long to installation. So after a few google search I find here. TinyTex it small, I expected that TinyTex will take less time to install, but unfortrunately no. I was stuck at the very beginning. Can you please just hide all the technical details (R? Powershell? or anything else? who care what tech you are using? people just want it get work done.) behind one button?

**Comment by yihui** [comment]
> who care what tech you are using?

Sorry, but we must care, because a software package is usually not designed for one person, and people use different technologies. We can't force them all to use one technology.

I appreciate that you point out the instructions may be unclear, and I'd like to know more about your situation. I'm curious why those questions are hard for you to answer (e.g., do you use R or PowerShell).

**Comment by aokman** [comment]
It doesn't matter about technology. Good softwares in real world usually assume that users have zero knowledge about the technology it used in background. Your product requires too many knowledge, users have to read a long readme to learn just on how to install it on their own machine. Although I sometimes used PowerShell(I never touched R), I still failed to install it on my machine after about half hour reading and tweaking (TinyTex was designed to save others' time, right?). Why not just do like what Tex Live does, provide some .bat or shell, and just one button click, all work done?

**Comment by aokman** [comment]
I just what to use it writing some articles. Now before writing, I have to learn many technologies, if I don't, I even can't start writing because I can't install the software.

**Comment by yihui** [comment]
> just one button click, all work done

That's exactly what we do. Just one click on the `.bat` file and all work is done: https://yihui.org/tinytex/#for-other-users

**Comment by aokman** [comment]
It seems like it's downloading something but failed. Why not drop the .bat in the zip, skip the download step, make it all in one as a single install package.
