### ISSUE TITLE
Need a newer build

### ISSUE THREAD

**Issue by gaborcsardi** [rstudio/tinytex-releases#42]
I don't really understand why a ~ 9 days old build would not be good enough, but apparently it is not. The current daily is from 2024-01-31 and it fails with 
```
tlmgr itself needs to be updated.
Please do this via either
...
```
If I call `tlmgr update --self` then it installs revision 69686 (2024-02-03), which is fine.

I guess this issues solves itself soonish, but if possible if would be great to have an early update to fix `r-lib/actions/setup-tinytex`. 

Cf. https://github.com/r-lib/actions/issues/801

**Comment by cderv** [comment]
We are downloading from a ctan mirror
```
--2024-02-08 03:13:14--  https://ctan.math.illinois.edu/systems/texlive/tlnet/install-tl-unx.tar.gz
```

It is the latest bundle they provide, so it seems something is off in tinytex infrastructure and what mirrors offers. I don't know how to build a more recent version... I'll check the next daily build to see if this is better. 

@yihui did you see anything mentioned in the tlmgr mailing list or website maybe ?

**Comment by yihui** [comment]
@cderv I didn't. I think you did the right thing by triggering a new daily build: https://github.com/rstudio/tinytex/actions/runs/7836686635 Let's see if it fixes the problem.

> I don't really understand why a ~ 9 days old build would not be good enough, but apparently it is not.

@gaborcsardi Actually it's not 9 days old but less than 24 hours old... This is unlikely but could happen (e.g., TeX Live team released a newer version of `tlmgr` right after we built the daily version).

**Comment by gaborcsardi** [comment]
Thank you both! So, if there is a new `tlmgr` release, that means that users *have to* update to that? In that case would it make sense to always try to update in the `r-lib/actions/setup-tinytex` action, no?

**Comment by yihui** [comment]
> if there is a new `tlmgr` release, that means that users **have to** update to that?

Not necessarily---only when users need to run `tlmgr` for installing or updating LaTeX packages from CTAN (as I said, this problem has been handled in `tinytex::tlmgr_install()` so users of the R package **tinytex** shouldn't run into it, but only those who run `tlmgr install` directly will hit it). In other cases, TinyTeX should just be fine. 

> In that case would it make sense to always try to update in the `r-lib/actions/setup-tinytex` action?

I don't have an opinion. This problem is not very likely to occur. On the other hand, `tlmgr update --self` takes a few seconds. That's the only cost. I'll let you decide whether it's worth it.

**Comment by gaborcsardi** [comment]
OK, in that case we'll suggest that if people need to run `tlmgr install` to install extra packages, then they should run `tlmgr update --self` first. Thanks!

**Comment by cderv** [comment]
Thanks ! The daily build version is now 
```
tlmgr revision 69686 (2024-02-03 08:34:54 +0100)
TeX Live (https://tug.org/texlive) version 2023
```

So we're good I think.
