### ISSUE TITLE
Locale 'Chinese (Simplified)_China.936' is unsupported, and may crash the interpreter.

### ISSUE THREAD

**Issue by xiaoluolorn** [rstudio/tinytex-releases#43]
TinyTeX-1-v2024.03.13 
Locale 'Chinese (Simplified)_China.936' is unsupported, and may crash the interpreter.

**Comment by yihui** [comment]
Next time please provide a more detailed description on how to reproduce the problem. A single message is often too little information for others to help you.

Anyway, it seems you are using Windows. If you are on Windows 10 (November 2019 update) or newer version, I'd suggest you change your locale to UTF-8 from the control panel.

**Comment by yihui** [comment]
Please see https://github.com/rstudio/tinytex/issues/439#issuecomment-2022655063.
